-- seed.sql
--
-- GENERATED FILE — do not edit by hand.
-- Regenerate with: pnpm gen:seed-sql
--
-- Sources of truth:
--   packages/domain/src/exercise-library.ts  (exercises, exercise_aliases)
--   packages/domain/src/benchmark-library.ts (benchmark_definitions)
-- packages/domain/src/exercise-library.test.ts fails if this file drifts.
--
-- Depends on migrations:
--   0001_extensions_and_enums.sql  (public.movement_pattern, public.activity_modality,
--                                   public.benchmark_scoring)
--   0003_exercise_library.sql      (public.exercises, public.exercise_aliases)
--   0006_benchmarks.sql            (public.benchmark_definitions)
--
-- Global reference data only: no user_id anywhere, every statement is
-- idempotent (`on conflict do nothing`), so re-running the seed is safe.

-- 81 canonical exercises.
insert into public.exercises (
    slug,
    name,
    movement_pattern,
    primary_muscles,
    secondary_muscles,
    equipment,
    is_unilateral,
    is_bodyweight,
    is_active
)
values
    ('back-squat', 'Back squat', 'squat'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['spinal erectors', 'adductors', 'core']::text[], array['barbell', 'squat rack']::text[], false, false, true),
    ('front-squat', 'Front squat', 'squat'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['upper back', 'core']::text[], array['barbell', 'dumbbell']::text[], false, false, true),
    ('air-squat', 'Air squat', 'squat'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['calves', 'core']::text[], array[]::text[], false, true, true),
    ('goblet-squats', 'Goblet squats', 'squat'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['core']::text[], array['dumbbell', 'kettlebell']::text[], false, false, true),
    ('sumo-squats', 'Sumo squats', 'squat'::public.movement_pattern, array['quadriceps', 'adductors']::text[], array['glutes']::text[], array[]::text[], false, true, true),
    ('wall-sit', 'Wall sit (hold)', 'squat'::public.movement_pattern, array['quadriceps']::text[], array['glutes']::text[], array['wall']::text[], false, true, true),
    ('jump-squats', 'Jump squats', 'power'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['calves']::text[], array[]::text[], false, true, true),
    ('bulgarian-split-squats', 'Bulgarian split squats', 'unilateral_leg'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['adductors', 'core']::text[], array['dumbbell', 'bench']::text[], true, false, true),
    ('step-ups', 'Step-ups', 'unilateral_leg'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['calves', 'core']::text[], array['box', 'dumbbell']::text[], true, false, true),
    ('forward-lunges', 'Forward lunges', 'unilateral_leg'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['hamstrings']::text[], array['dumbbell']::text[], true, true, true),
    ('lateral-lunges', 'Lateral lunges', 'unilateral_leg'::public.movement_pattern, array['adductors', 'glutes']::text[], array['quadriceps']::text[], array[]::text[], true, true, true),
    ('deadlift', 'Deadlift', 'hinge'::public.movement_pattern, array['hamstrings', 'glutes', 'spinal erectors']::text[], array['lats', 'traps', 'forearms']::text[], array['barbell', 'hex bar', 'dumbbell']::text[], false, false, true),
    ('romanian-deadlift', 'Romanian deadlift', 'hinge'::public.movement_pattern, array['hamstrings', 'glutes']::text[], array['spinal erectors', 'lats']::text[], array['barbell', 'dumbbell']::text[], false, false, true),
    ('single-leg-rdl', 'Single-leg RDL', 'hinge'::public.movement_pattern, array['hamstrings', 'glutes']::text[], array['core']::text[], array['dumbbell']::text[], true, false, true),
    ('hip-thrusts', 'Hip thrusts (floor)', 'hinge'::public.movement_pattern, array['glutes']::text[], array['hamstrings']::text[], array['mat']::text[], false, true, true),
    ('cable-leg-curl', 'Cable leg curl', 'hinge'::public.movement_pattern, array['hamstrings']::text[], array['calves']::text[], array['cable machine']::text[], true, false, true),
    ('kb-swings', 'Dumbbell/kettlebell swings', 'power'::public.movement_pattern, array['glutes', 'hamstrings']::text[], array['shoulders', 'core']::text[], array['dumbbell', 'kettlebell']::text[], false, false, true),
    ('bench-press', 'Bench press', 'horizontal_push'::public.movement_pattern, array['chest']::text[], array['triceps', 'front delts']::text[], array['barbell', 'bench']::text[], false, false, true),
    ('incline-dumbbell-press', 'Incline dumbbell press', 'horizontal_push'::public.movement_pattern, array['chest']::text[], array['front delts', 'triceps']::text[], array['dumbbell', 'bench']::text[], false, false, true),
    ('floor-press', 'DB/KB floor press', 'horizontal_push'::public.movement_pattern, array['chest', 'triceps']::text[], array['front delts']::text[], array['dumbbell', 'kettlebell', 'mat']::text[], false, false, true),
    ('push-ups', 'Push-ups', 'horizontal_push'::public.movement_pattern, array['chest', 'triceps']::text[], array['front delts', 'core']::text[], array[]::text[], false, true, true),
    ('parallette-push-ups', 'Parallette push-ups', 'horizontal_push'::public.movement_pattern, array['chest', 'triceps']::text[], array['front delts', 'core']::text[], array['parallettes']::text[], false, true, true),
    ('dips', 'Dips', 'vertical_push'::public.movement_pattern, array['chest', 'triceps']::text[], array['front delts']::text[], array['parallel bars']::text[], false, true, true),
    ('bent-over-rows', 'Bent-over row', 'horizontal_pull'::public.movement_pattern, array['lats', 'rhomboids']::text[], array['biceps', 'spinal erectors']::text[], array['barbell', 'dumbbell']::text[], false, false, true),
    ('chest-supported-row', 'Chest-supported row', 'horizontal_pull'::public.movement_pattern, array['lats', 'rhomboids']::text[], array['biceps', 'rear delts']::text[], array['dumbbell', 'bench']::text[], false, false, true),
    ('seated-cable-row', 'Seated cable row', 'horizontal_pull'::public.movement_pattern, array['lats', 'rhomboids']::text[], array['biceps', 'rear delts']::text[], array['cable machine']::text[], false, false, true),
    ('single-arm-row', 'Single-arm supported row', 'horizontal_pull'::public.movement_pattern, array['lats']::text[], array['biceps', 'rear delts']::text[], array['dumbbell', 'bench']::text[], true, false, true),
    ('renegade-rows', 'Renegade rows', 'horizontal_pull'::public.movement_pattern, array['lats']::text[], array['core', 'biceps']::text[], array['dumbbell']::text[], true, false, true),
    ('reverse-fly', 'Reverse fly', 'horizontal_pull'::public.movement_pattern, array['rear delts']::text[], array['rhomboids', 'traps']::text[], array['dumbbell']::text[], false, false, true),
    ('cable-rear-delt-fly', 'Single-arm cable rear-delt fly', 'horizontal_pull'::public.movement_pattern, array['rear delts']::text[], array['rhomboids']::text[], array['cable machine']::text[], true, false, true),
    ('pull-ups', 'Pull-ups', 'vertical_pull'::public.movement_pattern, array['lats']::text[], array['biceps', 'forearms', 'core']::text[], array['pull-up bar']::text[], false, true, true),
    ('pull-ups-strict', 'Strict pull-ups', 'vertical_pull'::public.movement_pattern, array['lats']::text[], array['biceps', 'forearms']::text[], array['pull-up bar']::text[], false, true, true),
    ('pull-ups-kipping', 'Kipping pull-ups', 'vertical_pull'::public.movement_pattern, array['lats']::text[], array['core', 'hip flexors', 'shoulders']::text[], array['pull-up bar']::text[], false, true, true),
    ('pull-ups-wide-grip', 'Wide-grip pull-ups', 'vertical_pull'::public.movement_pattern, array['lats']::text[], array['rhomboids', 'biceps']::text[], array['pull-up bar']::text[], false, true, true),
    ('pull-ups-weighted', 'Weighted strict pull-ups', 'vertical_pull'::public.movement_pattern, array['lats']::text[], array['biceps', 'forearms']::text[], array['pull-up bar', 'weight vest', 'dip belt']::text[], false, false, true),
    ('muscle-up', 'Muscle-up', 'vertical_pull'::public.movement_pattern, array['lats']::text[], array['triceps', 'chest', 'core']::text[], array['pull-up bar', 'rings']::text[], false, true, true),
    ('lat-pulldown', 'Lat pulldown', 'vertical_pull'::public.movement_pattern, array['lats']::text[], array['biceps', 'rhomboids']::text[], array['cable machine']::text[], false, false, true),
    ('dead-hang', 'Dead hang', 'vertical_pull'::public.movement_pattern, array['forearms']::text[], array['lats', 'shoulders']::text[], array['pull-up bar']::text[], false, true, true),
    ('cable-biceps-curl', 'Cable biceps curl', 'vertical_pull'::public.movement_pattern, array['biceps']::text[], array['forearms']::text[], array['cable machine']::text[], false, false, true),
    ('hammer-curls', 'DB/KB hammer curls', 'vertical_pull'::public.movement_pattern, array['biceps']::text[], array['forearms']::text[], array['dumbbell', 'kettlebell']::text[], false, false, true),
    ('overhead-press', 'DB/KB overhead press', 'vertical_push'::public.movement_pattern, array['shoulders']::text[], array['triceps', 'core']::text[], array['dumbbell', 'kettlebell', 'bench']::text[], false, false, true),
    ('cable-lateral-raise', 'Single-arm cable lateral raise', 'vertical_push'::public.movement_pattern, array['side delts']::text[], array['traps']::text[], array['cable machine']::text[], true, false, true),
    ('rope-triceps-pressdown', 'Rope triceps pressdown', 'vertical_push'::public.movement_pattern, array['triceps']::text[], array['forearms']::text[], array['cable machine']::text[], false, false, true),
    ('skull-crusher', 'Two-handed skull crusher', 'vertical_push'::public.movement_pattern, array['triceps']::text[], array['front delts']::text[], array['dumbbell', 'mat']::text[], false, false, true),
    ('clean-and-press', 'DB/KB clean and press', 'power'::public.movement_pattern, array['shoulders', 'glutes']::text[], array['quadriceps', 'triceps']::text[], array['dumbbell', 'kettlebell']::text[], false, false, true),
    ('windmills', 'DB/KB windmills', 'mobility'::public.movement_pattern, array['obliques', 'shoulders']::text[], array['hamstrings']::text[], array['dumbbell', 'kettlebell']::text[], true, false, true),
    ('thrusters', 'Thrusters', 'power'::public.movement_pattern, array['quadriceps', 'shoulders']::text[], array['glutes', 'triceps']::text[], array['dumbbell', 'barbell']::text[], false, false, true),
    ('burpees', 'Burpee variations', 'power'::public.movement_pattern, array['chest', 'quadriceps']::text[], array['core', 'shoulders']::text[], array[]::text[], false, true, true),
    ('devil-press', 'Devil press', 'power'::public.movement_pattern, array['shoulders', 'hamstrings']::text[], array['chest', 'glutes']::text[], array['dumbbell']::text[], false, false, true),
    ('wall-ball', 'Wall ball shots', 'power'::public.movement_pattern, array['quadriceps', 'shoulders']::text[], array['glutes', 'chest']::text[], array['wall ball', 'wall']::text[], false, false, true),
    ('man-makers', 'Man makers', 'power'::public.movement_pattern, array['chest', 'shoulders']::text[], array['core', 'quadriceps']::text[], array['dumbbell']::text[], false, false, true),
    ('jumping-jacks', 'Jumping jacks', 'locomotion'::public.movement_pattern, array['calves', 'shoulders']::text[], array['quadriceps']::text[], array[]::text[], false, true, true),
    ('high-knees', 'High knees', 'locomotion'::public.movement_pattern, array['hip flexors', 'calves']::text[], array['quadriceps']::text[], array[]::text[], false, true, true),
    ('rope-jumps', 'Rope jumps', 'locomotion'::public.movement_pattern, array['calves']::text[], array['shoulders']::text[], array['jump rope']::text[], false, true, true),
    ('farmer-carry', 'Farmer carry', 'carry'::public.movement_pattern, array['forearms', 'traps']::text[], array['core', 'glutes']::text[], array['dumbbell', 'kettlebell']::text[], false, false, true),
    ('overhead-carry', 'Overhead carry (hold)', 'carry'::public.movement_pattern, array['shoulders']::text[], array['core', 'traps']::text[], array['dumbbell', 'kettlebell']::text[], false, false, true),
    ('sled-push', 'Sled push', 'carry'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['calves', 'core']::text[], array['sled']::text[], false, false, true),
    ('plank', 'Plank', 'core'::public.movement_pattern, array['abs']::text[], array['shoulders', 'glutes']::text[], array[]::text[], false, true, true),
    ('shoulder-taps', 'Shoulder taps (plank)', 'core'::public.movement_pattern, array['abs', 'shoulders']::text[], array['chest']::text[], array[]::text[], false, true, true),
    ('russian-twists', 'Russian twists', 'core'::public.movement_pattern, array['obliques']::text[], array['abs', 'hip flexors']::text[], array['dumbbell']::text[], false, true, true),
    ('kneeling-cable-crunch', 'Kneeling cable crunch', 'core'::public.movement_pattern, array['abs']::text[], array['obliques']::text[], array['cable machine']::text[], false, false, true),
    ('core-abs', 'Core ABS', 'core'::public.movement_pattern, array['abs']::text[], array['obliques', 'hip flexors']::text[], array[]::text[], false, true, true),
    ('superman', 'Superman', 'core'::public.movement_pattern, array['spinal erectors', 'glutes']::text[], array['shoulders']::text[], array[]::text[], false, true, true),
    ('outdoor-run', 'Outdoor run', 'locomotion'::public.movement_pattern, array['quadriceps', 'hamstrings', 'calves']::text[], array['glutes', 'core']::text[], array[]::text[], false, true, true),
    ('treadmill-run', 'Treadmill run', 'locomotion'::public.movement_pattern, array['quadriceps', 'hamstrings', 'calves']::text[], array['glutes', 'core']::text[], array['treadmill']::text[], false, true, true),
    ('treadmill-walk', 'Treadmill walk', 'locomotion'::public.movement_pattern, array['calves', 'glutes']::text[], array['quadriceps']::text[], array['treadmill']::text[], false, true, true),
    ('walk', 'Walk', 'locomotion'::public.movement_pattern, array['calves', 'glutes']::text[], array['quadriceps']::text[], array[]::text[], false, true, true),
    ('hike', 'Hike', 'locomotion'::public.movement_pattern, array['quadriceps', 'glutes', 'calves']::text[], array['core']::text[], array[]::text[], false, true, true),
    ('bike-ride', 'Bike ride', 'locomotion'::public.movement_pattern, array['quadriceps', 'glutes']::text[], array['hamstrings', 'calves']::text[], array['bicycle']::text[], false, false, true),
    ('air-bike', 'Air bike', 'locomotion'::public.movement_pattern, array['quadriceps', 'shoulders']::text[], array['glutes', 'lats']::text[], array['air bike']::text[], false, false, true),
    ('row-erg', 'Rowing machine', 'locomotion'::public.movement_pattern, array['lats', 'quadriceps']::text[], array['hamstrings', 'biceps', 'core']::text[], array['rowing machine']::text[], false, false, true),
    ('ski-erg', 'Ski machine', 'locomotion'::public.movement_pattern, array['lats', 'triceps']::text[], array['core', 'quadriceps']::text[], array['ski erg']::text[], false, false, true),
    ('swim', 'Swimming', 'locomotion'::public.movement_pattern, array['lats', 'shoulders']::text[], array['core', 'quadriceps']::text[], array[]::text[], false, true, true),
    ('surfing', 'Surfing', 'locomotion'::public.movement_pattern, array['shoulders', 'lats']::text[], array['core', 'quadriceps']::text[], array['surfboard']::text[], false, false, true),
    ('kayaking', 'Kayaking', 'locomotion'::public.movement_pattern, array['lats', 'shoulders']::text[], array['core', 'biceps']::text[], array['kayak']::text[], false, false, true),
    ('dance', 'Dance training', 'locomotion'::public.movement_pattern, array['quadriceps', 'calves']::text[], array['core', 'shoulders']::text[], array[]::text[], false, true, true),
    ('stretching', 'Stretching', 'mobility'::public.movement_pattern, array[]::text[], array[]::text[], array['mat']::text[], false, true, true),
    ('foam-rolling', 'Foam rolling', 'mobility'::public.movement_pattern, array[]::text[], array[]::text[], array['foam roller']::text[], false, true, true),
    ('joint-mobility', 'Joint mobility', 'mobility'::public.movement_pattern, array[]::text[], array[]::text[], array[]::text[], false, true, true),
    ('lat-stretch', 'Lat stretch and release', 'mobility'::public.movement_pattern, array['lats']::text[], array['shoulders']::text[], array['foam roller']::text[], false, true, true),
    ('massage', 'Massage', 'mobility'::public.movement_pattern, array[]::text[], array[]::text[], array[]::text[], false, false, true)
on conflict do nothing;

-- 297 aliases, joined to their exercise by slug.
insert into public.exercise_aliases (exercise_id, alias, language, is_misspelling)
select e.id, v.alias, v.language, v.is_misspelling
from (
    values
    ('back-squat', 'back squat', 'en', false),
    ('back-squat', 'back squats', 'en', false),
    ('front-squat', 'front squat', 'en', false),
    ('front-squat', 'front squats', 'en', false),
    ('air-squat', 'air squats', 'en', false),
    ('air-squat', 'air squat', 'en', false),
    ('air-squat', 'squats', 'en', false),
    ('air-squat', 'squat', 'en', false),
    ('air-squat', 'bodyweight squats', 'en', false),
    ('air-squat', 'weighted squats', 'en', false),
    ('goblet-squats', 'goblet squats', 'en', false),
    ('goblet-squats', 'goblet squat', 'en', false),
    ('sumo-squats', 'sumo squats', 'en', false),
    ('sumo-squats', 'sumo squat', 'en', false),
    ('wall-sit', 'wall sit', 'en', false),
    ('wall-sit', 'wall sits', 'en', false),
    ('jump-squats', 'jump squats', 'en', false),
    ('jump-squats', 'jump squat', 'en', false),
    ('jump-squats', 'squat jumps', 'en', false),
    ('bulgarian-split-squats', 'bulgarian split squat', 'en', false),
    ('bulgarian-split-squats', 'bulgarian split squats', 'en', false),
    ('bulgarian-split-squats', 'split squat', 'en', false),
    ('step-ups', 'box step-ups', 'en', false),
    ('step-ups', 'box step ups', 'en', false),
    ('step-ups', 'step-ups', 'en', false),
    ('step-ups', 'step ups', 'en', false),
    ('step-ups', 'step up', 'en', false),
    ('forward-lunges', 'forward lunges', 'en', false),
    ('forward-lunges', 'forward lunge', 'en', false),
    ('forward-lunges', 'lunges', 'en', false),
    ('forward-lunges', 'lunge', 'en', false),
    ('forward-lunges', 'lunges with dumbbells', 'en', false),
    ('lateral-lunges', 'lateral lunges', 'en', false),
    ('lateral-lunges', 'lateral lunge', 'en', false),
    ('lateral-lunges', 'side lunges', 'en', false),
    ('deadlift', 'deadlift', 'en', false),
    ('deadlift', 'deadlifts', 'en', false),
    ('deadlift', 'test deadlifts', 'en', false),
    ('deadlift', 'deadlift with hex bar', 'en', false),
    ('deadlift', 'deadlifts with hex bar', 'en', false),
    ('deadlift', 'hex bar deadlift', 'en', false),
    ('deadlift', 'trap bar deadlift', 'en', false),
    ('deadlift', 'deadlifts with db', 'en', false),
    ('deadlift', 'deadlift with db', 'en', false),
    ('deadlift', 'dumbbell deadlift', 'en', false),
    ('deadlift', 'db deadlifts', 'en', false),
    ('deadlift', 'dl', 'abbr', false),
    ('deadlift', 'deadlifw', 'en', true),
    ('deadlift', 'deadlifw with hex bar', 'en', true),
    ('deadlift', 'dead lift', 'en', true),
    ('romanian-deadlift', 'romanian deadlift', 'en', false),
    ('romanian-deadlift', 'barbell romanian deadlift', 'en', false),
    ('romanian-deadlift', 'romanian deadlifts', 'en', false),
    ('romanian-deadlift', 'rdl', 'abbr', false),
    ('single-leg-rdl', 'single-leg rdl', 'en', false),
    ('single-leg-rdl', 'single leg rdl', 'en', false),
    ('single-leg-rdl', 'single-leg romanian deadlift', 'en', false),
    ('hip-thrusts', 'hip thrusts', 'en', false),
    ('hip-thrusts', 'hip thrust', 'en', false),
    ('hip-thrusts', 'glute bridge', 'en', false),
    ('cable-leg-curl', 'cable leg curl', 'en', false),
    ('cable-leg-curl', 'leg curl', 'en', false),
    ('cable-leg-curl', 'leg curls', 'en', false),
    ('kb-swings', 'dumbbell swings', 'en', false),
    ('kb-swings', 'db swings', 'en', false),
    ('kb-swings', 'kettlebell swings', 'en', false),
    ('kb-swings', 'kb swings', 'en', false),
    ('kb-swings', 'swings', 'en', false),
    ('bench-press', 'bench press', 'en', false),
    ('bench-press', 'barbell bench press', 'en', false),
    ('incline-dumbbell-press', 'incline dumbbell press', 'en', false),
    ('incline-dumbbell-press', 'incline db press', 'en', false),
    ('floor-press', 'floor press', 'en', false),
    ('floor-press', 'dumbbell floor press', 'en', false),
    ('floor-press', 'db floor press', 'en', false),
    ('push-ups', 'push ups', 'en', false),
    ('push-ups', 'push-ups', 'en', false),
    ('push-ups', 'pushups', 'en', false),
    ('push-ups', 'push up', 'en', false),
    ('push-ups', 'push-up', 'en', false),
    ('push-ups', 'max push ups', 'en', false),
    ('parallette-push-ups', 'parallettes', 'en', false),
    ('parallette-push-ups', 'parallette push ups', 'en', false),
    ('parallette-push-ups', 'push ups on parallettes', 'en', false),
    ('parallette-push-ups', 'paralets', 'en', true),
    ('parallette-push-ups', 'push ups without paralets', 'en', true),
    ('dips', 'dips', 'en', false),
    ('dips', 'dip', 'en', false),
    ('dips', 'tricep dips', 'en', false),
    ('dips', 'dips attempts', 'en', false),
    ('bent-over-rows', 'bent over barbell row', 'en', false),
    ('bent-over-rows', 'bent-over barbell row', 'en', false),
    ('bent-over-rows', 'barbell row', 'en', false),
    ('bent-over-rows', 'bent over row', 'en', false),
    ('bent-over-rows', 'bent over rows', 'en', false),
    ('bent-over-rows', 'bent-over rows', 'en', false),
    ('chest-supported-row', 'chest-supported row', 'en', false),
    ('chest-supported-row', 'chest supported row', 'en', false),
    ('seated-cable-row', 'seated cable row', 'en', false),
    ('seated-cable-row', 'low row', 'en', false),
    ('seated-cable-row', 'cable row', 'en', false),
    ('seated-cable-row', 'seated row', 'en', false),
    ('single-arm-row', 'single-arm supported row', 'en', false),
    ('single-arm-row', 'single arm row', 'en', false),
    ('single-arm-row', 'one arm row', 'en', false),
    ('renegade-rows', 'renegade rows', 'en', false),
    ('renegade-rows', 'renegade row', 'en', false),
    ('reverse-fly', 'reverse fly', 'en', false),
    ('reverse-fly', 'reverse flies', 'en', false),
    ('cable-rear-delt-fly', 'single-arm cable rear-delt fly', 'en', false),
    ('cable-rear-delt-fly', 'single arm cable rear delt fly', 'en', false),
    ('cable-rear-delt-fly', 'cable rear-delt fly', 'en', false),
    ('cable-rear-delt-fly', 'rear delt fly', 'en', false),
    ('pull-ups', 'pull ups', 'en', false),
    ('pull-ups', 'pull-ups', 'en', false),
    ('pull-ups', 'pull up', 'en', false),
    ('pull-ups', 'pull-up', 'en', false),
    ('pull-ups', 'pullups', 'en', false),
    ('pull-ups', 'chin ups', 'en', false),
    ('pull-ups-strict', 'strict pull ups', 'en', false),
    ('pull-ups-strict', 'strict pull-ups', 'en', false),
    ('pull-ups-strict', 'pull ups strict', 'en', false),
    ('pull-ups-strict', 'pull-ups strict', 'en', false),
    ('pull-ups-strict', 'strict pull up', 'en', false),
    ('pull-ups-strict', 'strict pull-up', 'en', false),
    ('pull-ups-kipping', 'pull kipping', 'en', false),
    ('pull-ups-kipping', 'kipping pull-up', 'en', false),
    ('pull-ups-kipping', 'kipping pull ups', 'en', false),
    ('pull-ups-kipping', 'kipping pull-ups', 'en', false),
    ('pull-ups-kipping', 'kipping', 'en', false),
    ('pull-ups-kipping', 'pull ups kipping', 'en', false),
    ('pull-ups-wide-grip', 'wide grip pull ups', 'en', false),
    ('pull-ups-wide-grip', 'wide-grip pull ups', 'en', false),
    ('pull-ups-wide-grip', 'wide grip pull-up', 'en', false),
    ('pull-ups-wide-grip', 'wide-grip pull-up', 'en', false),
    ('pull-ups-weighted', 'weighted strict pull-up', 'en', false),
    ('pull-ups-weighted', 'weighted pull-up', 'en', false),
    ('pull-ups-weighted', 'weighted pull ups', 'en', false),
    ('pull-ups-weighted', 'weighted pull-ups', 'en', false),
    ('muscle-up', 'muscle up', 'en', false),
    ('muscle-up', 'muscle-up', 'en', false),
    ('muscle-up', 'muscle ups', 'en', false),
    ('muscle-up', 'mu', 'abbr', false),
    ('lat-pulldown', 'lat pulldown', 'en', false),
    ('lat-pulldown', 'lat pull down', 'en', false),
    ('lat-pulldown', 'lat pulldowns', 'en', false),
    ('dead-hang', 'dead hang', 'en', false),
    ('dead-hang', 'deadhang', 'en', false),
    ('dead-hang', 'bar hang', 'en', false),
    ('cable-biceps-curl', 'cable biceps curl', 'en', false),
    ('cable-biceps-curl', 'cable bicep curl', 'en', false),
    ('cable-biceps-curl', 'cable curl', 'en', false),
    ('hammer-curls', 'bicep hammer exercise', 'en', false),
    ('hammer-curls', 'hammer curls', 'en', false),
    ('hammer-curls', 'hammer curl', 'en', false),
    ('hammer-curls', 'db hammer curls', 'en', false),
    ('overhead-press', 'overhead press', 'en', false),
    ('overhead-press', 'strict press', 'en', false),
    ('overhead-press', 'seated dumbbell overhead press', 'en', false),
    ('overhead-press', 'seated db overhead press', 'en', false),
    ('overhead-press', 'db overhead press', 'en', false),
    ('overhead-press', 'shoulder press', 'en', false),
    ('cable-lateral-raise', 'single-arm lateral raise cable', 'en', false),
    ('cable-lateral-raise', 'single arm lateral raise cable', 'en', false),
    ('cable-lateral-raise', 'cable lateral raise', 'en', false),
    ('cable-lateral-raise', 'lateral raise', 'en', false),
    ('rope-triceps-pressdown', 'rope triceps pressdown', 'en', false),
    ('rope-triceps-pressdown', 'rope tricep pressdown', 'en', false),
    ('rope-triceps-pressdown', 'triceps pressdown', 'en', false),
    ('rope-triceps-pressdown', 'rope pressdown', 'en', false),
    ('skull-crusher', 'skull crusher', 'en', false),
    ('skull-crusher', 'skull crushers', 'en', false),
    ('clean-and-press', 'clean and press', 'en', false),
    ('clean-and-press', 'clean & press', 'en', false),
    ('windmills', 'windmills', 'en', false),
    ('windmills', 'windmill', 'en', false),
    ('thrusters', 'thrusters', 'en', false),
    ('thrusters', 'thruster', 'en', false),
    ('thrusters', 'dumbbell thrusters', 'en', false),
    ('thrusters', 'db thrusters', 'en', false),
    ('burpees', 'burpees', 'en', false),
    ('burpees', 'burpee', 'en', false),
    ('devil-press', 'devil press', 'en', false),
    ('devil-press', 'devils press', 'en', false),
    ('devil-press', 'devil presses', 'en', false),
    ('wall-ball', 'wall balls', 'en', false),
    ('wall-ball', 'wall ball', 'en', false),
    ('wall-ball', 'wall ball shots', 'en', false),
    ('man-makers', 'man makers', 'en', false),
    ('man-makers', 'man maker', 'en', false),
    ('jumping-jacks', 'jumping jacks', 'en', false),
    ('jumping-jacks', 'jumping jack', 'en', false),
    ('high-knees', 'high knees', 'en', false),
    ('rope-jumps', 'rope jumps', 'en', false),
    ('rope-jumps', 'jump rope', 'en', false),
    ('rope-jumps', 'skipping', 'en', false),
    ('farmer-carry', 'farmer carry', 'en', false),
    ('farmer-carry', 'farmers carry', 'en', false),
    ('farmer-carry', 'farmer''s carry', 'en', false),
    ('overhead-carry', 'overhead carry', 'en', false),
    ('overhead-carry', 'overhead hold', 'en', false),
    ('sled-push', 'sled push', 'en', false),
    ('sled-push', 'sled pushes', 'en', false),
    ('sled-push', 'sled', 'en', false),
    ('plank', 'plank', 'en', false),
    ('plank', 'planks', 'en', false),
    ('shoulder-taps', 'shoulder taps', 'en', false),
    ('shoulder-taps', 'plank shoulder taps', 'en', false),
    ('russian-twists', 'russian twists', 'en', false),
    ('russian-twists', 'russian twist', 'en', false),
    ('kneeling-cable-crunch', 'kneeling cable crunch', 'en', false),
    ('kneeling-cable-crunch', 'cable crunch', 'en', false),
    ('core-abs', 'abs', 'en', false),
    ('core-abs', 'core abs', 'en', false),
    ('core-abs', 'crunches', 'en', false),
    ('superman', 'superman', 'en', false),
    ('superman', 'supermans', 'en', false),
    ('outdoor-run', 'outdoor run', 'en', false),
    ('outdoor-run', 'run', 'en', false),
    ('outdoor-run', 'running', 'en', false),
    ('outdoor-run', 'easy run', 'en', false),
    ('outdoor-run', 'beach run', 'en', false),
    ('outdoor-run', 'jog', 'en', false),
    ('outdoor-run', 'easy jog', 'en', false),
    ('treadmill-run', 'treadmill run', 'en', false),
    ('treadmill-run', 'treadmill easy run', 'en', false),
    ('treadmill-run', 'treadmill', 'en', false),
    ('treadmill-run', 'hotel treadmill run', 'en', false),
    ('treadmill-run', 'run on a treadmill', 'en', false),
    ('treadmill-run', 'treadmil', 'en', true),
    ('treadmill-walk', 'treadmill walk', 'en', false),
    ('treadmill-walk', 'walking treadmill', 'en', false),
    ('treadmill-walk', 'treadmill walking', 'en', false),
    ('walk', 'walk', 'en', false),
    ('walk', 'walking', 'en', false),
    ('walk', 'steps walking', 'en', false),
    ('hike', 'hike', 'en', false),
    ('hike', 'hiking', 'en', false),
    ('hike', 'hiking uphill', 'en', false),
    ('hike', 'hiking downhill', 'en', false),
    ('hike', 'mini hike', 'en', false),
    ('bike-ride', 'bike to & from work', 'en', false),
    ('bike-ride', 'bike to and from work', 'en', false),
    ('bike-ride', 'biking to work', 'en', false),
    ('bike-ride', 'bike ride', 'en', false),
    ('bike-ride', 'easy bike ride', 'en', false),
    ('bike-ride', 'biking', 'en', false),
    ('bike-ride', 'extra biking', 'en', false),
    ('air-bike', 'air bike', 'en', false),
    ('air-bike', 'airbike', 'en', false),
    ('air-bike', 'rogue bike', 'en', false),
    ('air-bike', 'assault bike', 'en', false),
    ('air-bike', 'echo bike', 'en', false),
    ('air-bike', 'bike (rogue)', 'en', false),
    ('air-bike', 'kkal bike', 'en', true),
    ('air-bike', 'kkal rogue bike', 'en', true),
    ('row-erg', 'row machine', 'en', false),
    ('row-erg', 'rowing machine', 'en', false),
    ('row-erg', 'rowing', 'en', false),
    ('row-erg', 'row', 'en', false),
    ('row-erg', 'erg row', 'en', false),
    ('row-erg', 'concept2 row', 'en', false),
    ('row-erg', 'kkal row', 'en', true),
    ('ski-erg', 'ski machine', 'en', false),
    ('ski-erg', 'ski erg', 'en', false),
    ('ski-erg', 'skierg', 'en', false),
    ('swim', 'swimming', 'en', false),
    ('swim', 'swimming training', 'en', false),
    ('swim', 'swim', 'en', false),
    ('swim', 'front crawl', 'en', false),
    ('surfing', 'surfing', 'en', false),
    ('surfing', 'surfing training', 'en', false),
    ('surfing', 'surf', 'en', false),
    ('kayaking', 'kayaking', 'en', false),
    ('kayaking', 'light kayaking', 'en', false),
    ('kayaking', 'kayak', 'en', false),
    ('dance', 'dance training', 'en', false),
    ('dance', 'dance', 'en', false),
    ('dance', 'dancing', 'en', false),
    ('stretching', 'stretching', 'en', false),
    ('stretching', 'stretch', 'en', false),
    ('stretching', 'rolling and stretching', 'en', false),
    ('foam-rolling', 'foam rolling', 'en', false),
    ('foam-rolling', 'rolling', 'en', false),
    ('foam-rolling', 'rolling shoulders', 'en', false),
    ('foam-rolling', 'rolling buttocks', 'en', false),
    ('joint-mobility', 'joint mobility', 'en', false),
    ('joint-mobility', 'mobility', 'en', false),
    ('lat-stretch', 'lat stretch', 'en', false),
    ('lat-stretch', 'lats stretch', 'en', false),
    ('lat-stretch', 'rolling lats', 'en', false),
    ('lat-stretch', 'lads', 'en', true),
    ('lat-stretch', 'rolling lads', 'en', true),
    ('lat-stretch', 'stretching lads', 'en', true),
    ('massage', 'massage', 'en', false),
    ('massage', 'deep tissue massage', 'en', false),
    ('massage', 'sports massage', 'en', false)
) as v (slug, alias, language, is_misspelling)
join public.exercises e on e.slug = v.slug
on conflict do nothing;

-- 8 standard benchmarks. `prescription` carries the
-- movement breakdown, the recognised source phrasings and whether the standard
-- prescribes a vest; performed work lives in benchmark_results.
insert into public.benchmark_definitions (
    slug,
    name,
    scoring,
    modality,
    description,
    prescription,
    is_standard,
    is_active
)
values
    ('murph', 'Murph', 'time'::public.benchmark_scoring, 'hybrid_conditioning'::public.activity_modality, '1 mile run, 100 pull-ups, 200 push-ups, 300 air squats, 1 mile run, traditionally wearing a 9 kg vest. The middle movements may be partitioned in any order (the workbook logs Cindy-style rounds and hand-picked set sizes).', '{"supportsVest":true,"aliases":["murph","full murph","murph preparation","murph preperation"],"movements":[{"order":1,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":1.60934},{"order":2,"exerciseSlug":"pull-ups","reps":100,"distanceKm":null},{"order":3,"exerciseSlug":"push-ups","reps":200,"distanceKm":null},{"order":4,"exerciseSlug":"air-squat","reps":300,"distanceKm":null},{"order":5,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":1.60934}]}'::jsonb, true, true),
    ('half-murph', 'Half Murph', 'time'::public.benchmark_scoring, 'hybrid_conditioning'::public.activity_modality, 'Half of Murph: 800 m run, 50 pull-ups, 100 push-ups, 150 air squats, 800 m run, vest optional. The workbook runs ~1.5 km on each end rather than exactly 800 m.', '{"supportsVest":true,"aliases":["half murph","half-murph","1/2 murph"],"movements":[{"order":1,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":0.80467},{"order":2,"exerciseSlug":"pull-ups","reps":50,"distanceKm":null},{"order":3,"exerciseSlug":"push-ups","reps":100,"distanceKm":null},{"order":4,"exerciseSlug":"air-squat","reps":150,"distanceKm":null},{"order":5,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":0.80467}]}'::jsonb, true, true),
    ('cindy', 'Cindy', 'rounds_reps'::public.benchmark_scoring, 'hybrid_conditioning'::public.activity_modality, '20 minute AMRAP of 5 pull-ups, 10 push-ups, 15 air squats. The workbook usually logs a fixed number of rounds rather than a 20 minute cap, and often adds 50 jumping jacks per round or a loaded squat, which is a scaled variant.', '{"supportsVest":true,"aliases":["cindy","rounds cindy","cindy bodyweight"],"movements":[{"order":1,"exerciseSlug":"pull-ups","reps":5,"distanceKm":null},{"order":2,"exerciseSlug":"push-ups","reps":10,"distanceKm":null},{"order":3,"exerciseSlug":"air-squat","reps":15,"distanceKm":null}]}'::jsonb, true, true),
    ('row-1000m', '1000 m row', 'time'::public.benchmark_scoring, 'rowing'::public.activity_modality, '1000 m on the rowing machine for time. Secondary figure is the average 500 m split.', '{"supportsVest":false,"aliases":["1000 m row","1000m row","row 1000m","1k row"],"movements":[{"order":1,"exerciseSlug":"row-erg","reps":null,"distanceKm":1}]}'::jsonb, true, true),
    ('run-5k', '5 k run', 'time'::public.benchmark_scoring, 'running'::public.activity_modality, '5 km run for time, treadmill or outdoor.', '{"supportsVest":false,"aliases":["5 k","5k","5 km run","5km run"],"movements":[{"order":1,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":5}]}'::jsonb, true, true),
    ('run-10k', '10 k run', 'time'::public.benchmark_scoring, 'running'::public.activity_modality, '10 km run for time, treadmill or outdoor.', '{"supportsVest":false,"aliases":["10 k","10k","10 km run","10km run"],"movements":[{"order":1,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":10}]}'::jsonb, true, true),
    ('half-marathon', 'Half marathon', 'time'::public.benchmark_scoring, 'running'::public.activity_modality, '21.0975 km run for time.', '{"supportsVest":false,"aliases":["half marathon","half-marathon","21k","21.1 km"],"movements":[{"order":1,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":21.0975}]}'::jsonb, true, true),
    ('marathon', 'Marathon', 'time'::public.benchmark_scoring, 'running'::public.activity_modality, '42.195 km run for time.', '{"supportsVest":false,"aliases":["marathon","42.2 km"],"movements":[{"order":1,"exerciseSlug":"outdoor-run","reps":null,"distanceKm":42.195}]}'::jsonb, true, true)
on conflict do nothing;
